export const FROM_DATE_FILTER = "FROM_DATE_FILTER";
export const TO_DATE_FILTER = "TO_DATE_FILTER";
export const JOBS_STATUS_FILTER = "APPLY_JOBS_STAUTS_FILTER";
// user jobs
export const INITIATE_USER_JOBS_FETCH = "INITIATE_USER_JOBS_FETCH";
export const FETCH_USER_JOBS_SUCCESS = "FETCH_USER_JOBS_SUCCESS";
export const FETCH_USER_JOBS_FAILURE = "FETCH_USER_JOBS_FAILURE";
//file upload
export const INITIATE_FILE_UPLOAD = "INITIATE_FILE_UPLOAD";
export const FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS";
export const FILE_UPLOAD_FAILURE = "FILE_UPLOAD_FAILURE";
// job status retrieval
export const INITIATE_JOB_STATUS_RETRIEVAL = "INITIATE_JOB_STATUS_RETRIEVAL";
export const JOB_STATUS_RECEIVED = "JOB_STATUS_RECEIVED";
export const JOB_STATUS_FAILED_TO_RECEIVED = "JOB_STATUS_FAILED_TO_RECEIVED";
// upload definitions
export const INITIATE_UPLOAD_DEFINITIONS_FETCH =
  "INITIATE_UPLOAD_DEFINITIONS_FETCH";
export const UPLOAD_DEFINTIONS_RECEIVED = "UPLOAD_DEFINTIONS_RECEIVED";
export const FETCH_UPLOAD_DEFINITIONS_FAILURE =
  "FETCH_UPLOAD_DEFINITIONS_FAILURE";
// selected module and file types
export const MODULE_SELECTED = "MODULE_SELECTED";
export const FILE_TYPE_SELECTED = "FILE_TYPE_SELECTED";
