export const DATE_FILTER = "APPLY_DATE_FILTER";
export const JOBS_STATUS_FILTER = "APPLY_JOBS_STAUTS_FILTER";
export const INITIATE_USER_JOBS_FETCH = "INITIATE_USER_JOBS_FETCH";
export const FETCH_USER_JOBS_SUCCESS = "FETCH_USER_JOBS_SUCCESS";
export const FETCH_PLAYERS_FAILURE = "FETCH_PLAYERS_FAILURE";
