export const ADD_NEW_PLAYER_SUCCESS = 'ADD_NEW_PLAYER_SUCCESS';
export const REMOVE_PLAYER_SUCCESS = 'REMOVE_PLAYER_SUCCESS';
export const UPDATE_PLAYER_SUCCESS = 'UPDATE_PLAYER_SUCCESS';
export const FETCH_PLAYERS_SUCCESS = 'FETCH_PLAYERS_SUCCESS';
export const FETCH_PLAYERS_FAILURE = 'FETCH_PLAYERS_SUCCESS';